version: '3.8'
name: delivery
services:
  app:
    depends_on:
      - db
      - redis
      - keycloak
    #    restart: on-failure
    container_name: myapp
    image: delivery-delivery-infrastructure:1.0.0
    expose:
      - "8081"
    ports:
      - "8081:8081"
    build:
      context: ../../infrastructure
      dockerfile: docker/delivery-delivery-infrastructure/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mydb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=tomasz
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATA_REDIS_HOST=myredis
      - SPRING_PROFILES_ACTIVE=docker
  db:
    image: postgres
    container_name: mydb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=tomasz
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5434:5434"
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: [ "start-dev" ]
    depends_on:
      - db
    container_name: mykeycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
      #      - KC_HEALTH_ENABLED=true
      #      - KC_METRICS_ENABLED=true
      #      - KC_HOSTNAME=127.0.0.1
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
      - KC_DB=postgres
      - KC_DB_SCHEMA=public
      - KC_DB_URL=jdbc:postgresql://mydb:5432/postgres
      - KC_DB_USERNAME=tomasz
      - KC_DB_PASSWORD=password
    volumes:
      - keycloak-data:/data
      - /home/tomasz/Pobrane/realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  redis-data:
  keycloak-data: