version: '3.8'
name: delivery
services:
  app:
    depends_on:
      - db
    container_name: myapp
    image: delivery-delivery-infrastructure:1.0.0
    expose:
      - "8080"
    ports:
      - "8080:8080"
    build:
      context: ../../infrastructure
      dockerfile: docker/delivery-delivery-infrastructure/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mydb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=tomasz
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
  db:
    image: postgres
    container_name: mydb
    environment:
      - POSTGRES_DB=delivery
      - POSTGRES_USER=tomasz
      - POSTGRES_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    expose:
      - "5432"
    ports:
      - "5434:5434"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: